<?php

namespace App\Services;

use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;

class PredictionService
{
    /**
     * Memprediksi probabilitas kerusakan memanggil API FastAPI model SGD.
     * Menggunakan try-catch agar tidak memutus flow utama telemetri jika API down.
     */
    public function predictRisk(float $sisaJarakKm, float $durasiKemacetanMenit, float $suhuSaatIni, float $mktSejauhIni): array
    {
        try {
            // Load weights from JSON file generated by SGD model
            $weightsPath = base_path('ml/model_weights.json');
            if (file_exists($weightsPath)) {
                $weights = json_decode(file_get_contents($weightsPath), true);
                
                $fluktuasiMkt = $mktSejauhIni - 8.0;
                
                // SGDRegressor linear equation
                $prediksi = ($sisaJarakKm * $weights['koef_sisa_jarak']) +
                            ($durasiKemacetanMenit * $weights['koef_kemacetan']) +
                            ($fluktuasiMkt * $weights['koef_fluktuasi_mkt']) +
                            $weights['intercept'];
                            
                // Ensure probability is between 0 and 1
                $probabilitas = max(0, min(1, $prediksi));
                
                $instruksi = 'Kondisi aman, lanjutkan perjalanan.';
                if ($probabilitas > 0.7) {
                     $instruksi = 'Kritis! Segera periksa box vaksin dan hubungi fasilitas terdekat.';
                } elseif ($probabilitas > 0.4) {
                     $instruksi = 'Peringatan: Risiko kerusakan meningkat, pantau suhu.';
                }
                
                return [
                    'probabilitas_rusak' => round($probabilitas * 100, 2),
                    'instruksi_mitigasi' => $instruksi
                ];
            } else {
                Log::warning('File model_weights.json tidak ditemukan.');
            }
        } catch (\Exception $e) {
            Log::warning('Gagal memproses Prediksi AI: ' . $e->getMessage());
        }

        // Fallback rule-based jika gagal
        return [
            'probabilitas_rusak' => null,
            'instruksi_mitigasi' => 'Layanan AI Tidak Tersedia'
        ];
    }

    /**
     * Helper MVP: Hardcode estimasi jarak sisa dari titik kumpul awal (Dinkes Palembang)
     * ke lokasi tujuan spesifik (karena tabel perjalanan_rute belum menyimpan dest_latitude/longitude).
     * 
     * @param string $tujuan
     * @return float Jarak statis awal dalam KM 
     */
    public function getEstimatedRemainingDistance(string $tujuan, float $currentLat, float $currentLng): float
    {
        $faskes = \App\Models\InventoryHub::where('nama', $tujuan)->first();
        if ($faskes && $faskes->latitude && $faskes->longitude) {
            return $this->haversineDistance($currentLat, $currentLng, (float) $faskes->latitude, (float) $faskes->longitude);
        }

        return 0.0; // Fallback jika faskes tidak ditemukan
    }

    /**
     * Menghitung jarak antara 2 koordinat (Haversine formula) dalam Kilometer
     */
    private function haversineDistance($lat1, $lon1, $lat2, $lon2)
    {
        $earthRadius = 6371; // km
        
        $dLat = deg2rad($lat2 - $lat1);
        $dLon = deg2rad($lon2 - $lon1);
        
        $a = sin($dLat/2) * sin($dLat/2) + cos(deg2rad($lat1)) * cos(deg2rad($lat2)) * sin($dLon/2) * sin($dLon/2);
        $c = 2 * asin(sqrt($a));
        
        return $earthRadius * $c;
    }
}
